version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  #  BeforeInstall:
  #    - location: scripts/clean.sh 
  AfterInstall:
    - location: scripts/stop.sh # 엔진엑스와 연결되어 있지 않은 스프링 부트를 종료합니다.
      timeout: 60
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start.sh # 프론트 & 백엔드 어플리케이션을 실행합니다.
      timeout: 60
      runas: ec2-user
  ValidateService:
    - location: scripts/health.sh # 새 스프링 부트가 정상적으로 실행됐는지 확인 합니다.
      timeout: 60
      runas: ec2-user

# website
#hooks:
#  ApplicationStart:
#    - location: scripts/run_new_was.sh
#      timeout: 180
#      runas: ec2-user
#    - location: scripts/health_check.sh
#      timeout: 180
#      runas: ec2-user
#    - location: scripts/switch.sh
#      timeout: 180
#      runas: ec2-user