version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/maildog
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/clean.sh
  AfterInstall:
    - location: scripts/stop.sh
      timeout: 60x
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu
  ValidateService:
    - location: scripts/health.sh
      timeout: 60
      runas: ubuntu